package seqtool;

/**
 * @author scottcase
 */

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/** This class is sort of the main launcher class that starts up the rest of
 * the application. It's pretty sparse because all of the actual code that runs
 * the program is located elsewhere. Because I used FXML (generated by
 * SceneBuilder) to define the UI, most of the program is in the
 * FXMLDocumentController file.
 */

public class SeqTool extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("FXMLDocument" +
                ".fxml"));

        Scene scene = new Scene(root, 800, 600);

        stage.setScene(scene);
        stage.show();
    }

}
