package sequence;

import org.junit.Assert;
import org.junit.Test;

public class DNASequenceTest extends DNASequence {

    public DNASequenceTest() {
        super("gb|AE005174.2|:1411715-1412779 Escherichia coli O157:H7 EDL933, complete genome",
                "ATGGTAACGTCCTGTACTGGACATGTTTTAGATAATCAACGCGCCACCACTCGCGGAGTTTTCTCCTCCG" +
                        "GTAGTCATCTCGTCACTTTGCATTTTCAACCTCATCCTTTCTTTTCATGTGTTACCGACGCCGTAAACGG" +
                        "TGCGCGTAGCCGTTTTTCGGCATTTTATCCAAAAGCAAACTATGGCTTACAAGGAAGCCAACCCTCTGAT" +
                        "GTTCGTGCGCATAATCGCGCTGCCAACGGCGCGTGTGATGAATACAAACAACTCAAGGTGCTCTCCATGG" +
                        "GAAGACAAAAAGCAGTGATCAAAGCTCGTCGCGAGGCAAAACGTGTGCTGAGACGGGATTCGCGCAGCCA" +
                        "TAAGCAGCGTGAAGAAGAATCGGTCACCTCGCTTGTGCAGATGGGCGGCGTAGAAGCCATTGGTATGGCC" +
                        "CGCGACAGTCGCGATACTTCGCCCATCCTCGCGCGAAATGAAGCGCAATTGCACTATCTGAAGGCTATTG" +
                        "AGAGTAAGCAGCTGATATTCGCCACGGGCGAAGCCGGGTGCGGAAAAACCTGGATCAGCGCAGCAAAAGC" +
                        "GGCAGAGGCCCTGATACATAAGGATGTCGACAGGATTATCGTCACCCGTCCAGTTCTGCAAGCCGATGAA" +
                        "GATCTTGGCTTCTTACCTGGAGATATCGCAGAAAAGTTTGCTCCCTATTTTCGCCCGGTCTACGACGTGC" +
                        "TGGTCCGGCGCTTAGGGGCTTCCTTTATGCAGTACTGCCTGCGACCGGAAATAGGGAAGGTGGAAATTGC" +
                        "GCCGTTCGCCTATATGCGTGGACGTACCTTTGAAAATGCAGTCGTCATTCTTGACGAGGCGCAGAATGTG" +
                        "ACTGCCGCGCAAATGAAAATGTTTTTAACCCGCCTCGGGGAGAACGTGACGGTTATCGTCAACGGTGATA" +
                        "TCACGCAATGCGATTTGCCTCGCGGCGTGTGCTCCGGATTAAGTGACGCGCTGGAACGTTTCGAAGAAGA" +
                        "TGAAATGGTTGGGATCGTCCGGTTCGGAAAAGAGGATTGCGTACGTTCGGCACTTTGCCAACGTACGCTG" +
                        "CATGCATACAGTTAA");
    }

    @Test
    public void testComplement() throws Exception {
        String expected = "TACCATTGCAGGACATGACCTGTACAAAATCTATTAGTTGCGCGGTGGTGAGCGCCTCAAAAGAGGAGGC" +
                "CATCAGTAGAGCAGTGAAACGTAAAAGTTGGAGTAGGAAAGAAAAGTACACAATGGCTGCGGCATTTGCC" +
                "ACGCGCATCGGCAAAAAGCCGTAAAATAGGTTTTCGTTTGATACCGAATGTTCCTTCGGTTGGGAGACTA" +
                "CAAGCACGCGTATTAGCGCGACGGTTGCCGCGCACACTACTTATGTTTGTTGAGTTCCACGAGAGGTACC" +
                "CTTCTGTTTTTCGTCACTAGTTTCGAGCAGCGCTCCGTTTTGCACACGACTCTGCCCTAAGCGCGTCGGT" +
                "ATTCGTCGCACTTCTTCTTAGCCAGTGGAGCGAACACGTCTACCCGCCGCATCTTCGGTAACCATACCGG" +
                "GCGCTGTCAGCGCTATGAAGCGGGTAGGAGCGCGCTTTACTTCGCGTTAACGTGATAGACTTCCGATAAC" +
                "TCTCATTCGTCGACTATAAGCGGTGCCCGCTTCGGCCCACGCCTTTTTGGACCTAGTCGCGTCGTTTTCG" +
                "CCGTCTCCGGGACTATGTATTCCTACAGCTGTCCTAATAGCAGTGGGCAGGTCAAGACGTTCGGCTACTT" +
                "CTAGAACCGAAGAATGGACCTCTATAGCGTCTTTTCAAACGAGGGATAAAAGCGGGCCAGATGCTGCACG" +
                "ACCAGGCCGCGAATCCCCGAAGGAAATACGTCATGACGGACGCTGGCCTTTATCCCTTCCACCTTTAACG" +
                "CGGCAAGCGGATATACGCACCTGCATGGAAACTTTTACGTCAGCAGTAAGAACTGCTCCGCGTCTTACAC" +
                "TGACGGCGCGTTTACTTTTACAAAAATTGGGCGGAGCCCCTCTTGCACTGCCAATAGCAGTTGCCACTAT" +
                "AGTGCGTTACGCTAAACGGAGCGCCGCACACGAGGCCTAATTCACTGCGCGACCTTGCAAAGCTTCTTCT" +
                "ACTTTACCAACCCTAGCAGGCCAAGCCTTTTCTCCTAACGCATGCAAGCCGTGAAACGGTTGCATGCGAC" +
                "GTACGTATGTCAATT";
        String test = complement(super.getSeq());
        Assert.assertEquals(expected, test);
    }

    @Test
    public void testRevComplement() throws Exception {
        String expected =
                "TTAACTGTATGCATGCAGCGTACGTTGGCAAAGTGCCGAACGTACGCAATCCTCTTTTCCGAACCGGACGATCCC" +
                        "AACCATTTCATCTTCTTCGAAACGTTCCAGCGCGTCACTTAATCCGGAGCACACGCCGCGAGGCAAA" +
                        "TCGCATTGCGTGATATCACCGTTGACGATAACCGTCACGTTCTCCCCGAGGCGGGTTAAAAACATTT" +
                        "TCATTTGCGCGGCAGTCACATTCTGCGCCTCGTCAAGAATGACGACTGCATTTTCAAAGGTACGTCC" +
                        "ACGCATATAGGCGAACGGCGCAATTTCCACCTTCCCTATTTCCGGTCGCAGGCAGTACTGCATAAAG" +
                        "GAAGCCCCTAAGCGCCGGACCAGCACGTCGTAGACCGGGCGAAAATAGGGAGCAAACTTTTCTGCGA" +
                        "TATCTCCAGGTAAGAAGCCAAGATCTTCATCGGCTTGCAGAACTGGACGGGTGACGATAATCCTGTC" +
                        "GACATCCTTATGTATCAGGGCCTCTGCCGCTTTTGCTGCGCTGATCCAGGTTTTTCCGCACCCGGCT" +
                        "TCGCCCGTGGCGAATATCAGCTGCTTACTCTCAATAGCCTTCAGATAGTGCAATTGCGCTTCATTTC" +
                        "GCGCGAGGATGGGCGAAGTATCGCGACTGTCGCGGGCCATACCAATGGCTTCTACGCCGCCCATCTG" +
                        "CACAAGCGAGGTGACCGATTCTTCTTCACGCTGCTTATGGCTGCGCGAATCCCGTCTCAGCACACGT" +
                        "TTTGCCTCGCGACGAGCTTTGATCACTGCTTTTTGTCTTCCCATGGAGAGCACCTTGAGTTGTTTGT" +
                        "ATTCATCACACGCGCCGTTGGCAGCGCGATTATGCGCACGAACATCAGAGGGTTGGCTTCCTTGTAA" +
                        "GCCATAGTTTGCTTTTGGATAAAATGCCGAAAAACGGCTACGCGCACCGTTTACGGCGTCGGTAACA" +
                        "CATGAAAAGAAAGGATGAGGTTGAAAATGCAAAGTGACGAGATGACTACCGGAGGAGAAAACTCCGC" +
                        "GAGTGGTGGCGCGTTGATTATCTAAAACATGTCCAGTACAGGACGTTACCAT";
        String test = revComplement(super.getSeq());
        Assert.assertEquals(expected, test);
    }
}