package sequence;

import org.junit.Assert;
import org.junit.Test;


/**
 * Created by scottcase on 8/22/2015.
 */
public class SequenceTest extends Sequence {

    public SequenceTest() {
        super("gb|AE005174.2|:1411715-1412779 Escherichia coli O157:H7 EDL933, complete genome",
                "ATGGTAACGTCCTGTACTGGACATGTTTTAGATAATCAACGCGCCACCACTCGCGGAGTTTTCTCCTCCG" +
                "GTAGTCATCTCGTCACTTTGCATTTTCAACCTCATCCTTTCTTTTCATGTGTTACCGACGCCGTAAACGG" +
                "TGCGCGTAGCCGTTTTTCGGCATTTTATCCAAAAGCAAACTATGGCTTACAAGGAAGCCAACCCTCTGAT" +
                "GTTCGTGCGCATAATCGCGCTGCCAACGGCGCGTGTGATGAATACAAACAACTCAAGGTGCTCTCCATGG" +
                "GAAGACAAAAAGCAGTGATCAAAGCTCGTCGCGAGGCAAAACGTGTGCTGAGACGGGATTCGCGCAGCCA" +
                "TAAGCAGCGTGAAGAAGAATCGGTCACCTCGCTTGTGCAGATGGGCGGCGTAGAAGCCATTGGTATGGCC" +
                "CGCGACAGTCGCGATACTTCGCCCATCCTCGCGCGAAATGAAGCGCAATTGCACTATCTGAAGGCTATTG" +
                "AGAGTAAGCAGCTGATATTCGCCACGGGCGAAGCCGGGTGCGGAAAAACCTGGATCAGCGCAGCAAAAGC" +
                "GGCAGAGGCCCTGATACATAAGGATGTCGACAGGATTATCGTCACCCGTCCAGTTCTGCAAGCCGATGAA" +
                "GATCTTGGCTTCTTACCTGGAGATATCGCAGAAAAGTTTGCTCCCTATTTTCGCCCGGTCTACGACGTGC" +
                "TGGTCCGGCGCTTAGGGGCTTCCTTTATGCAGTACTGCCTGCGACCGGAAATAGGGAAGGTGGAAATTGC" +
                "GCCGTTCGCCTATATGCGTGGACGTACCTTTGAAAATGCAGTCGTCATTCTTGACGAGGCGCAGAATGTG" +
                "ACTGCCGCGCAAATGAAAATGTTTTTAACCCGCCTCGGGGAGAACGTGACGGTTATCGTCAACGGTGATA" +
                "TCACGCAATGCGATTTGCCTCGCGGCGTGTGCTCCGGATTAAGTGACGCGCTGGAACGTTTCGAAGAAGA" +
                "TGAAATGGTTGGGATCGTCCGGTTCGGAAAAGAGGATTGCGTACGTTCGGCACTTTGCCAACGTACGCTG" +
                "CATGCATACAGTTAA");
    }

    @Test
    public void testGetSeqAsLines() throws Exception {
        String expected = "ATGGTAACGTCCTGTACTGGACATGTTTTAGATAATCAACGCGCCACCACTCGCGGAGTTTTCTCCTCCG\n" +
                "GTAGTCATCTCGTCACTTTGCATTTTCAACCTCATCCTTTCTTTTCATGTGTTACCGACGCCGTAAACGG\n" +
                "TGCGCGTAGCCGTTTTTCGGCATTTTATCCAAAAGCAAACTATGGCTTACAAGGAAGCCAACCCTCTGAT\n" +
                "GTTCGTGCGCATAATCGCGCTGCCAACGGCGCGTGTGATGAATACAAACAACTCAAGGTGCTCTCCATGG\n" +
                "GAAGACAAAAAGCAGTGATCAAAGCTCGTCGCGAGGCAAAACGTGTGCTGAGACGGGATTCGCGCAGCCA\n" +
                "TAAGCAGCGTGAAGAAGAATCGGTCACCTCGCTTGTGCAGATGGGCGGCGTAGAAGCCATTGGTATGGCC\n" +
                "CGCGACAGTCGCGATACTTCGCCCATCCTCGCGCGAAATGAAGCGCAATTGCACTATCTGAAGGCTATTG\n" +
                "AGAGTAAGCAGCTGATATTCGCCACGGGCGAAGCCGGGTGCGGAAAAACCTGGATCAGCGCAGCAAAAGC\n" +
                "GGCAGAGGCCCTGATACATAAGGATGTCGACAGGATTATCGTCACCCGTCCAGTTCTGCAAGCCGATGAA\n" +
                "GATCTTGGCTTCTTACCTGGAGATATCGCAGAAAAGTTTGCTCCCTATTTTCGCCCGGTCTACGACGTGC\n" +
                "TGGTCCGGCGCTTAGGGGCTTCCTTTATGCAGTACTGCCTGCGACCGGAAATAGGGAAGGTGGAAATTGC\n" +
                "GCCGTTCGCCTATATGCGTGGACGTACCTTTGAAAATGCAGTCGTCATTCTTGACGAGGCGCAGAATGTG\n" +
                "ACTGCCGCGCAAATGAAAATGTTTTTAACCCGCCTCGGGGAGAACGTGACGGTTATCGTCAACGGTGATA\n" +
                "TCACGCAATGCGATTTGCCTCGCGGCGTGTGCTCCGGATTAAGTGACGCGCTGGAACGTTTCGAAGAAGA\n" +
                "TGAAATGGTTGGGATCGTCCGGTTCGGAAAAGAGGATTGCGTACGTTCGGCACTTTGCCAACGTACGCTG\n" +
                "CATGCATACAGTTAA";
        String test = this.getSeqAsLines(70);
        Assert.assertEquals(expected, test);
    }

    @Test
    public void testToString() throws Exception {
        String expected = ">gb|AE005174.2|:1411715-1412779 Escherichia coli O157:H7 EDL933, complete genome\n" +
                "ATGGTAACGTCCTGTACTGGACATGTTTTAGATAATCAACGCGCCACCACTCGCGGAGTTTTCTCCTCCG\n" +
                "GTAGTCATCTCGTCACTTTGCATTTTCAACCTCATCCTTTCTTTTCATGTGTTACCGACGCCGTAAACGG\n" +
                "TGCGCGTAGCCGTTTTTCGGCATTTTATCCAAAAGCAAACTATGGCTTACAAGGAAGCCAACCCTCTGAT\n" +
                "GTTCGTGCGCATAATCGCGCTGCCAACGGCGCGTGTGATGAATACAAACAACTCAAGGTGCTCTCCATGG\n" +
                "GAAGACAAAAAGCAGTGATCAAAGCTCGTCGCGAGGCAAAACGTGTGCTGAGACGGGATTCGCGCAGCCA\n" +
                "TAAGCAGCGTGAAGAAGAATCGGTCACCTCGCTTGTGCAGATGGGCGGCGTAGAAGCCATTGGTATGGCC\n" +
                "CGCGACAGTCGCGATACTTCGCCCATCCTCGCGCGAAATGAAGCGCAATTGCACTATCTGAAGGCTATTG\n" +
                "AGAGTAAGCAGCTGATATTCGCCACGGGCGAAGCCGGGTGCGGAAAAACCTGGATCAGCGCAGCAAAAGC\n" +
                "GGCAGAGGCCCTGATACATAAGGATGTCGACAGGATTATCGTCACCCGTCCAGTTCTGCAAGCCGATGAA\n" +
                "GATCTTGGCTTCTTACCTGGAGATATCGCAGAAAAGTTTGCTCCCTATTTTCGCCCGGTCTACGACGTGC\n" +
                "TGGTCCGGCGCTTAGGGGCTTCCTTTATGCAGTACTGCCTGCGACCGGAAATAGGGAAGGTGGAAATTGC\n" +
                "GCCGTTCGCCTATATGCGTGGACGTACCTTTGAAAATGCAGTCGTCATTCTTGACGAGGCGCAGAATGTG\n" +
                "ACTGCCGCGCAAATGAAAATGTTTTTAACCCGCCTCGGGGAGAACGTGACGGTTATCGTCAACGGTGATA\n" +
                "TCACGCAATGCGATTTGCCTCGCGGCGTGTGCTCCGGATTAAGTGACGCGCTGGAACGTTTCGAAGAAGA\n" +
                "TGAAATGGTTGGGATCGTCCGGTTCGGAAAAGAGGATTGCGTACGTTCGGCACTTTGCCAACGTACGCTG\n" +
                "CATGCATACAGTTAA";
        String test = this.toString();
        Assert.assertEquals(expected, test);
    }
}